// Generated by codegen/generate.ts from mawaqit/api-spec v0.4.0. Do not edit.

import type { APIClient, RequestOptions } from '../core.ts';
import type { Account } from '../types.ts';

/** The parameters of `client.auth.login()`. */
export interface AuthLoginParams {
  /** Email of the MAWAQIT account. */
  email: string;

  /** Password of the MAWAQIT account. */
  password: string;
}

/** Get an API token. */
export class Auth {
  readonly #client: APIClient;

  constructor(client: APIClient) {
    this.#client = client;
  }

  /**
   * Log in.
   *
   * Return the account of an email and password, with its API token.
   *
   * The token is created on the first call and stays the same afterwards, so it can be stored
   * instead of the password.
   *
   * @param params - The parameters, see {@link AuthLoginParams}.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The account.
   * @throws {AuthenticationError} Wrong email or password.
   * @throws {APIError} The request failed in another way.
   */
  login(params: AuthLoginParams, options?: RequestOptions): Promise<Account> {
    return this.#client.request(
      {
        method: 'POST',
        path: '/2.0/me',
        basicAuth: [params.email, params.password],
        authenticated: false,
      },
      options,
    );
  }
}
