// Generated by codegen/generate.ts from mawaqit/api-spec v0.5.1. Do not edit.

import type { APIClient, RequestOptions } from '../core.ts';
import type { Hadith } from '../types.ts';

/** The parameters of `client.hadiths.random()`. */
export interface HadithsRandomParams {
  /**
   * Language of the hadith: `ar`, `de`, `en`, `es`, `fi`, `fr`, `nl`, `pt`, `ta` or `tr`. A pair
   * with Arabic, like `fr-ar`, draws one of its two languages at random, like the `hadithLang` of
   * the mosque screens. Any other value gives Arabic. `ar` by default.
   */
  lang?: string;

  /**
   * The text is shorter than this many bytes of UTF-8, where an Arabic letter takes 2. Ignored when
   * `lang` is `ta`: the hadith is then shorter than 1000 bytes. At least 1, 500 by default.
   */
  maxLength?: number;
}

/** Read the hadiths shown on the mosque screens. */
export class Hadiths {
  readonly #client: APIClient;

  constructor(client: APIClient) {
    this.#client = client;
  }

  /**
   * Get a random hadith.
   *
   * Return a hadith drawn at random among those of a language shorter than `maxLength`, or `null`
   * when none is short enough.
   *
   * Responses are cached for an hour: the same parameters return the same hadith for up to an hour.
   *
   * @param params - The parameters, see {@link HadithsRandomParams}.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The hadith, or `null` when none is short enough.
   * @throws {APIError} The request failed in another way.
   */
  random(params: HadithsRandomParams = {}, options?: RequestOptions): Promise<Hadith | null> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/2.0/hadith/random',
        query: { lang: params.lang, maxLength: params.maxLength },
        authenticated: false,
        emptyAsNull: true,
      },
      options,
    );
  }
}
