// Generated by codegen/generate.ts from mawaqit/api-spec v0.4.0. Do not edit.

import type { APIClient, RequestOptions } from '../core.ts';
import type {
  FlashMessage,
  HijriSettings,
  Mosque,
  MosqueConfig,
  MosqueSummary,
  PrayerTimes,
} from '../types.ts';

/** The parameters of `client.mosques.search()`. */
export type MosquesSearchParams = MosquesSearchByWordsParams | MosquesSearchAroundPositionParams;

/** The parameters of `client.mosques.search()`, by words. */
export interface MosquesSearchByWordsParams {
  /**
   * Words to look for in the name and address of the mosques. Only the first 30 characters are
   * used.
   */
  word: string;
  lat?: never;
  lon?: never;
  radius?: never;
  /** Page of results. At least 1, 1 by default. */
  page?: number;
  /** Number of mosques per page. From 1 to 50, 10 by default. */
  itemsPerPage?: number;
}

/** The parameters of `client.mosques.search()`, around a position. */
export interface MosquesSearchAroundPositionParams {
  word?: never;
  /** Latitude of the position to search around, in degrees. From -90 to 90. */
  lat: number;
  /** Longitude of the position to search around, in degrees. From -180 to 180. */
  lon: number;
  /** Initial search radius around the position, in kilometers. From 1 to 20, 5 by default. */
  radius?: number;
  /** Page of results. At least 1, 1 by default. */
  page?: number;
  /** Number of mosques per page. From 1 to 50, 10 by default. */
  itemsPerPage?: number;
}

/** Search mosques and read their prayer times. */
export class Mosques {
  readonly #client: APIClient;

  constructor(client: APIClient) {
    this.#client = client;
  }

  /**
   * Search mosques.
   *
   * Search mosques by name and address, or around a position.
   *
   * A position takes precedence over `word`. Around a position, mosques come nearest first, and the
   * search radius grows by 5 km up to 20 km until a mosque is found. Without a `word` of 2
   * characters or more and without a position, the result is empty.
   *
   * @param params - The parameters, see {@link MosquesSearchParams}.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The mosques found, possibly none.
   * @throws {APIError} The request failed in another way.
   */
  search(params: MosquesSearchParams, options?: RequestOptions): Promise<Mosque[]> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/2.0/mosque/search',
        query: {
          word: params.word,
          lat: params.lat,
          lon: params.lon,
          radius: params.radius,
          page: params.page,
          itemsPerPage: params.itemsPerPage,
        },
        authenticated: false,
      },
      options,
    );
  }

  /**
   * Get a mosque by its ID.
   *
   * Return the UUID, name and type of a mosque from its ID.
   *
   * Homes and the other places that are not mosques are not returned by `client.mosques.search()`:
   * their owners find them with their ID, shown next to each of their places in the MAWAQIT back
   * office.
   *
   * @param mosqueId - ID of the mosque. At least 1.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The mosque.
   * @throws {AuthenticationError} Missing, invalid or disabled API token.
   * @throws {PermissionDeniedError} The account has used all the API calls of its quota.
   * @throws {NotFoundError} No published mosque has this ID.
   * @throws {APIError} The request failed in another way.
   */
  get(mosqueId: number, options?: RequestOptions): Promise<MosqueSummary> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/3.0/mosque/{mosqueId}',
        pathParams: { mosqueId },
        authenticated: true,
      },
      options,
    );
  }

  /**
   * Get prayer times.
   *
   * Return the information, prayer times and iqama times of a mosque for the whole year.
   *
   * Responses are cached for a long time: `times`, `shuruq` and the Jumu'a times describe the day
   * the response was generated, so read the times of a given day from `calendar` and
   * `iqamaCalendar` instead.
   *
   * @param uuid - UUID of the mosque, as returned by `client.mosques.search()` or
   *   `client.mosques.get()`.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The prayer times of the mosque.
   * @throws {AuthenticationError} Missing, invalid or disabled API token.
   * @throws {PermissionDeniedError} The account has used all the API calls of its quota.
   * @throws {NotFoundError} No published mosque has this UUID.
   * @throws {APIError} The request failed in another way.
   */
  prayerTimes(uuid: string, options?: RequestOptions): Promise<PrayerTimes> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/2.0/mosque/{uuid}/prayer-times',
        pathParams: { uuid },
        authenticated: true,
      },
      options,
    );
  }

  /**
   * Get Hijri date settings.
   *
   * Return how the Hijri date of a mosque is computed: the Kuwaiti algorithm on today's date
   * shifted by `hijriAdjustment` days, with the day replaced by 30 when `hijriDateForceTo30` is
   * `true`.
   *
   * These settings change around the start of the Hijri months, after the moon sighting, sometimes
   * for every mosque of a country at once. Read them from this endpoint rather than from
   * `client.mosques.prayerTimes()`, whose copy can lag behind.
   *
   * @param uuid - UUID of the mosque, as returned by `client.mosques.search()` or
   *   `client.mosques.get()`.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The Hijri date settings of the mosque.
   * @throws {AuthenticationError} Missing, invalid or disabled API token.
   * @throws {PermissionDeniedError} The account has used all the API calls of its quota.
   * @throws {NotFoundError} No published mosque has this UUID.
   * @throws {APIError} The request failed in another way.
   */
  hijriSettings(uuid: string, options?: RequestOptions): Promise<HijriSettings> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/3.0/mosque/{uuid}/hijri-date',
        pathParams: { uuid },
        authenticated: true,
      },
      options,
    );
  }

  /**
   * Get the screen settings.
   *
   * Return the settings of the mosque screens: what they display, the adhan and iqama options, and
   * whether the mosque displays Sabah and Imsak.
   *
   * @param uuid - UUID of the mosque, as returned by `client.mosques.search()` or
   *   `client.mosques.get()`.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The screen settings of the mosque.
   * @throws {AuthenticationError} Missing, invalid or disabled API token.
   * @throws {PermissionDeniedError} The account has used all the API calls of its quota.
   * @throws {NotFoundError} No published mosque has this UUID.
   * @throws {APIError} The request failed in another way.
   */
  config(uuid: string, options?: RequestOptions): Promise<MosqueConfig> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/3.0/mosque/{uuid}/config',
        pathParams: { uuid },
        authenticated: true,
      },
      options,
    );
  }

  /**
   * Get the flash message.
   *
   * Return the flash message of a mosque, or `null` when it has none.
   *
   * The message is returned before its `startDate` and after its `endDate` too: the mosque screens
   * show it from `startDate` to `endDate` included, in the time zone of the mosque. The same
   * message is in the `flash` of `client.mosques.prayerTimes()`, a much larger response.
   *
   * @param uuid - UUID of the mosque, as returned by `client.mosques.search()` or
   *   `client.mosques.get()`.
   * @param options - Options of this request, like its `timeout` or `signal`.
   * @returns The flash message of the mosque, or `null`.
   * @throws {AuthenticationError} Missing, invalid or disabled API token.
   * @throws {PermissionDeniedError} The account has used all the API calls of its quota.
   * @throws {NotFoundError} No published mosque has this UUID.
   * @throws {APIError} The request failed in another way.
   */
  flashMessage(uuid: string, options?: RequestOptions): Promise<FlashMessage | null> {
    return this.#client.request(
      {
        method: 'GET',
        path: '/3.0/mosque/{uuid}/flash-message',
        pathParams: { uuid },
        authenticated: true,
      },
      options,
    );
  }
}
