// Generated by codegen/generate.ts from mawaqit/api-spec v0.4.0. Do not edit.

import { APIClient } from './core.ts';
import { Auth } from './resources/auth.ts';
import { Mosques } from './resources/mosques.ts';

/**
 * The client of the MAWAQIT API.
 *
 * ```ts
 * const client = new Mawaqit(); // Reads MAWAQIT_TOKEN.
 * const [mosque] = await client.mosques.search({ lat: 48.8414, lon: 2.3557 });
 * if (mosque) {
 *   const prayerTimes = await client.mosques.prayerTimes(mosque.uuid);
 * }
 * ```
 */
export class Mawaqit extends APIClient {
  /** Get an API token. */
  readonly auth: Auth = new Auth(this);

  /** Search mosques and read their prayer times. */
  readonly mosques: Mosques = new Mosques(this);
}
