// Generated by codegen/generate.ts from mawaqit/api-spec v0.4.0. Do not edit.

/** A MAWAQIT account and its API access. */
export interface Account {
  /** ID of the account. */
  id: number;

  /** API token of the account, to send in the `Api-Access-Token` header. */
  apiAccessToken: string;

  /** Number of API calls the account is allowed to make. `0` or `null` means unlimited. */
  apiQuota: number | null;

  /** Number of API calls the account has made. */
  apiCallNumber: number | null;
}

/** A mosque found by a search. */
export interface Mosque {
  /** UUID of the mosque, used by the other endpoints. */
  uuid: string;

  /** Name of the mosque. */
  name: string;

  /** Name to display for the mosque. */
  label: string;

  /** Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`. */
  type: string;

  /** Identifier of the mosque in its MAWAQIT page URL. */
  slug: string | null;

  /** Latitude of the mosque, in degrees. */
  latitude: number;

  /** Longitude of the mosque, in degrees. */
  longitude: number;

  /** Address of the mosque, in one line. */
  localisation: string;

  /**
   * Distance from the position of the search, in meters. Only present in a search around a
   * position.
   */
  proximity?: number;

  /** Name of the association that runs the mosque. */
  associationName: string | null;

  /** Phone number of the mosque. */
  phone: string | null;

  /** Email address of the mosque. */
  email: string | null;

  /** Website of the mosque. */
  site: string | null;

  /** Website to donate to the mosque. */
  paymentWebsite: string | null;

  /** URL of the picture of the mosque, or of a default picture when it has none. */
  image: string;

  /**
   * Why the mosque is closed: `ADMINISTRATIVE`, `MAINTENANCE`, `PERMANENT` or `OTHER`. `null` when
   * it is open.
   */
  closed: string | null;

  /** Whether the mosque has a space for women. `null` when unknown. */
  womenSpace: boolean | null;

  /** Whether the mosque holds funeral prayers. `null` when unknown. */
  janazaPrayer: boolean | null;

  /** Whether the mosque holds the Eid prayers. `null` when unknown. */
  aidPrayer: boolean | null;

  /** Whether the mosque gives courses to children. `null` when unknown. */
  childrenCourses: boolean | null;

  /** Whether the mosque gives courses to adults. `null` when unknown. */
  adultCourses: boolean | null;

  /** Whether the mosque serves iftar meals during Ramadan. `null` when unknown. */
  ramadanMeal: boolean | null;

  /** Whether the mosque is accessible to people with disabilities. `null` when unknown. */
  handicapAccessibility: boolean | null;

  /** Whether the mosque has an ablution room. `null` when unknown. */
  ablutions: boolean | null;

  /** Whether the mosque has a car park. `null` when unknown. */
  parking: boolean | null;

  /**
   * Today's Fajr, Shuruq, Dhuhr, Asr, Maghrib and Isha times, as HH:MM in the time zone of the
   * mosque. `null` when the mosque has no prayer times.
   */
  times: string[] | null;

  /**
   * Today's iqama of Fajr, Dhuhr, Asr, Maghrib and Isha, either as HH:MM or as `+N`, N minutes
   * after the adhan. `null` when the mosque has no prayer times.
   */
  iqama: string[] | null;

  /** Time of the first Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua: string | null;

  /** Time of the second Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua2: string | null;

  /** Time of the third Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua3: string | null;

  /** Whether Jumu'a is prayed at the time of Dhuhr. */
  jumuaAsDuhr: boolean;

  /** Whether the mosque publishes iqama times. */
  iqamaEnabled: boolean;
}

/** A mosque found by its ID. */
export interface MosqueSummary {
  /** ID of the mosque. */
  id: number;

  /** UUID of the mosque, used by the other endpoints. */
  uuid: string;

  /** Name of the mosque. */
  name: string;

  /** Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`. */
  type: string;

  /** Address of the mosque, in one line. */
  localisation: string;

  /** URL of the picture of the mosque, or of a default picture when it has none. */
  image: string;
}

/** The information and prayer times of a mosque for the year. */
export interface PrayerTimes {
  /** Numeric ID of the mosque. */
  id: number;

  /** UUID of the mosque. */
  uuid: string;

  /** Name of the mosque, followed by its city if the mosque chose so. */
  name: string;

  /** Name to display for the mosque, same as `name`. */
  label: string;

  /** Kind of place: `MOSQUE`, `MUSALLA`, `HOME`, `SCHOOL`, `STORE` or `ASSOCIATION`. */
  type: string;

  /** Whether the mosque is a MAWAQIT partner. */
  partner: boolean;

  /** URL of the MAWAQIT page of the mosque. */
  url: string;

  /** URL of the live audio stream of the mosque. */
  streamUrl: string | null;

  /** Address of the mosque, in one line. */
  localisation: string;

  /** Country of the mosque, as an ISO 3166-1 alpha-2 code. */
  countryCode: string;

  /** IANA time zone of the mosque. Every time of this response is in this time zone. */
  timezone: string;

  /** Latitude of the mosque, in degrees. */
  latitude: number;

  /** Longitude of the mosque, in degrees. */
  longitude: number;

  /** Name of the association that runs the mosque. */
  association: string | null;

  /** Phone number of the mosque. */
  phone: string | null;

  /** Email address of the mosque. */
  email: string | null;

  /** Website of the mosque. */
  site: string | null;

  /** Website to donate to the mosque. */
  paymentWebsite: string | null;

  /** URL of the main picture of the mosque. */
  image: string | null;

  /** URL of a picture of the inside of the mosque. */
  interiorPicture: string | null;

  /** URL of a picture of the outside of the mosque. */
  exteriorPicture: string | null;

  /** URL of the logo of the mosque. */
  logo: string | null;

  /** Other information published by the mosque. */
  otherInfo: string | null;

  /**
   * Why the mosque is closed: `ADMINISTRATIVE`, `MAINTENANCE`, `PERMANENT` or `OTHER`. `null` when
   * it is open.
   */
  closed: string | null;

  /** Whether the mosque has a space for women. `null` when unknown. */
  womenSpace: boolean | null;

  /** Whether the mosque holds funeral prayers. `null` when unknown. */
  janazaPrayer: boolean | null;

  /** Whether the mosque holds the Eid prayers. `null` when unknown. */
  aidPrayer: boolean | null;

  /** Whether the mosque gives courses to children. `null` when unknown. */
  childrenCourses: boolean | null;

  /** Whether the mosque gives courses to adults. `null` when unknown. */
  adultCourses: boolean | null;

  /** Whether the mosque serves iftar meals during Ramadan. `null` when unknown. */
  ramadanMeal: boolean | null;

  /** Whether the mosque is accessible to people with disabilities. `null` when unknown. */
  handicapAccessibility: boolean | null;

  /** Whether the mosque has an ablution room. `null` when unknown. */
  ablutions: boolean | null;

  /** Whether the mosque has a car park. `null` when unknown. */
  parking: boolean | null;

  /** The announcements of the mosque. */
  announcements: Announcement[];

  /** The announcements that have both a start and an end date. */
  events: Announcement[];

  /**
   * A short message scrolling at the bottom of the mosque screens. Absent when the mosque has none.
   */
  flash?: FlashMessage;

  /**
   * Prayer times of the year, one item per month from January to December. Each month maps its
   * days, from `"1"`, to the Fajr, Shuruq, Dhuhr, Asr, Maghrib and Isha times, as HH:MM. Mosques
   * that display Imsak have 7 times a day: Imsak, Sabah (used as Fajr), Shuruq, Dhuhr, Asr, Maghrib
   * and Isha. Times entered by hand by the mosque can be invalid.
   */
  calendar: Record<string, string[]>[];

  /**
   * Iqama times of the year, one item per month from January to December. Each month maps its days,
   * from `"1"`, to the iqama of Fajr, Dhuhr, Asr, Maghrib and Isha, either as HH:MM or as `+N`, N
   * minutes after the adhan.
   */
  iqamaCalendar: Record<string, string[]>[];

  /**
   * Fajr, Dhuhr, Asr, Maghrib and Isha times of the day the response was generated, as HH:MM.
   * Prefer `calendar`.
   */
  times: string[];

  /** Shuruq time of the day the response was generated, as HH:MM. Prefer `calendar`. */
  shuruq: string;

  /** Time of the first Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua: string | null;

  /** Time of the second Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua2: string | null;

  /** Time of the third Jumu'a prayer, as HH:MM. `null` when there is none. */
  jumua3: string | null;

  /**
   * Whether Jumu'a is prayed at the time of Dhuhr. `jumua` is then the Dhuhr time of the next
   * Friday.
   */
  jumuaAsDuhr: boolean;

  /** Time of the first Eid prayer, as HH:MM. */
  aidPrayerTime: string | null;

  /** Time of the second Eid prayer, as HH:MM. */
  aidPrayerTime2: string | null;

  /** Time of the third Eid prayer, as HH:MM. */
  aidPrayerTime3: string | null;

  /** Number of minutes between Imsak and Fajr. */
  imsakNbMinBeforeFajr: number | null;

  /** Whether the mosque publishes iqama times. */
  iqamaEnabled: boolean;

  /**
   * Number of days added to the date before computing the Hijri date. Prefer
   * `client.mosques.hijriSettings()`.
   */
  hijriAdjustment: number;

  /**
   * Whether the day of the Hijri date is replaced by 30. Prefer `client.mosques.hijriSettings()`.
   */
  hijriDateForceTo30: boolean;
}

/** How the Hijri date of a mosque is computed. */
export interface HijriSettings {
  /**
   * Number of days added to today's date before computing the Hijri date, usually between -2 and 2.
   */
  hijriAdjustment: number;

  /**
   * Whether the day of the Hijri date is replaced by 30, when a month lasts one more day than the
   * Kuwaiti algorithm expects.
   */
  hijriDateForceTo30: boolean;
}

/** The settings of the screens of a mosque. */
export interface MosqueConfig {
  /** Whether the city is shown after the name of the mosque. */
  showCityInTitle: boolean;

  /** Whether the logo of the mosque is shown. */
  showLogo: boolean;

  /** Whether the prayer times are shown on the screen of the announcements. */
  showPrayerTimesOnMessageScreen: boolean;

  /** Whether a hadith about the behavior during Jumu'a is shown during it. */
  jumuaDhikrReminderEnabled: boolean;

  /** Whether the screen turns black during Jumu'a. */
  jumuaBlackScreenEnabled: boolean;

  /** Approximate duration of Jumu'a, sermon and prayer, in minutes. */
  jumuaTimeout: number;

  /** Approximate duration of Fajr, Dhuhr, Asr, Maghrib and Isha, in minutes, as strings. */
  duaAfterPrayerShowTimes: string[];

  /** Whether the Hijri date is shown. */
  hijriDateEnabled: boolean;

  /**
   * Whether the day of the Hijri date is replaced by 30. Prefer `client.mosques.hijriSettings()`.
   */
  hijriDateForceTo30: boolean;

  /** Whether the dua after the adhan is shown. */
  duaAfterAzanEnabled: boolean;

  /** Whether the invocations after the prayer are shown. */
  duaAfterPrayerEnabled: boolean;

  /** Adhan played by the screens, `null` for a beep. */
  adhanVoice: string | null;

  /** Whether the adhan is played at Fajr, Dhuhr, Asr, Maghrib and Isha, as `"1"` or `"0"`. */
  adhanEnabledByPrayer: string[];

  /** Approximate duration of the adhan, in seconds. */
  adhanDuration: number;

  /** URL of the adhan recorded by the mosque, if any. */
  customAthan: string | null;

  /** Duration of the adhan recorded by the mosque, in seconds. */
  customAthanDuration: number | null;

  /** Whether a sound is played at the iqama. */
  iqamaBip: boolean;

  /** Sound played at the iqama. */
  iqamaBipSound: string | null;

  /** Whether the countdown to the iqama takes the whole screen. */
  iqamaFullScreenCountdown: boolean;

  /** How long the iqama signal is shown, in seconds. */
  iqamaDisplayTime: number;

  /** Whether the mosque publishes iqama times. */
  iqamaEnabled: boolean;

  /** Whether the iqama times are highlighted rather than the adhan times. */
  iqamaMoreImportant: boolean | null;

  /** Whether iqama times are always shown as HH:MM, rather than as minutes after the adhan. */
  alwaysDisplayHhMmFormat: boolean;

  /** Whether the screen turns black during the prayers. */
  blackScreenWhenPraying: boolean;

  /** Minutes before Fajr of a first adhan to wake up, `null` for none. */
  wakeForFajrTime: number | null;

  /** Fajr is set this many minutes before Shuruq, `null` when it is not. */
  fajrFixationComparedToShuruq: number | null;

  /** Whether a random hadith is shown every 5 minutes. */
  randomHadithEnabled: boolean;

  /** Between which prayers the hadiths are not shown, like during lessons. */
  randomHadithIntervalDisabling: string | null;

  /** Language of the hadiths, like `ar`. */
  hadithLang: string;

  /** Whether the outside temperature is shown. */
  temperatureEnabled: boolean;

  /** Unit of the temperature: `C` or `F`. */
  temperatureUnit: string;

  /** Time format of the screens: `24` or `12`. */
  timeDisplayFormat: string;

  /** Theme of the screens, like `mawaqit`. */
  theme: string;

  /** Background of the screens: `motif` or `color`. */
  backgroundType: string;

  /** ID of the background pattern. */
  backgroundMotif: string;

  /** Background color, as a CSS hex color. */
  backgroundColor: string;

  /** URL of the background picture of the screens. */
  backgroundUrl: string | null;

  /** Whether the footer is shown. */
  footer: boolean;

  /** Whether the MAWAQIT logo and QR code are shown on Android TV. */
  displayQrCodeAndLogoOnAndroidTV: boolean;

  /**
   * Whether the mosque displays Sabah and Imsak. Its `calendar` then has 7 times a day, see
   * `client.mosques.prayerTimes()`.
   */
  displayingSabahImsak: boolean;

  /** From when Sabah and Imsak are displayed. */
  sabahImsakStartDate: string | null;

  /** Until when Sabah and Imsak are displayed. */
  sabahImsakEndDate: string | null;
}

/** An announcement published by a mosque. */
export interface Announcement {
  /** ID of the announcement. */
  id: number;

  /** UUID of the mosque. */
  uuid: string;

  /** Title of the announcement. */
  title: string | null;

  /** Text of the announcement. */
  content: string | null;

  /** URL of the image of the announcement. */
  image: string | null;

  /** URL of the embedded video of the announcement. */
  video: string | null;

  /** When the announcement starts, as `YYYY-MM-DD HH:MM` in the time zone of the mosque. */
  startDate: string | null;

  /** When the announcement ends, as `YYYY-MM-DD HH:MM` in the time zone of the mosque. */
  endDate: string | null;

  /** When the announcement was last updated, as `YYYY-MM-DD HH:MM`. */
  updated: string | null;

  /** How long the announcement stays on the mosque screen, in seconds. */
  duration: number;

  /** Whether the announcement is shown in the mobile app. */
  isMobile: boolean;

  /** Whether the announcement is shown on the mosque screens. */
  isDesktop: boolean;

  /** Orientation of the announcement on the mosque screens: `LANDSCAPE` or `PORTRAIT`. */
  tvOrientation: string;
}

/**
 * A short message scrolling at the bottom of the mosque screens. The screens show it from
 * `startDate` to `endDate` included.
 */
export interface FlashMessage {
  /** Text of the message, limited to 200 characters by the back office. */
  content: string | null;

  /** UUID of the mosque. */
  uuid: string;

  /** First day of the message. */
  startDate: string | null;

  /** Last day of the message. */
  endDate: string | null;

  /**
   * Last day of the message, as a Unix timestamp. Use `endDate`.
   *
   * @deprecated Use `endDate`.
   */
  expire: number | null;

  /** Background color of the message, as a CSS hex color. */
  color: string;

  /** Direction of the text: `ltr` or `rtl`. */
  orientation: string;
}
